# -*- coding: utf-8 -*-
"""Untitled110.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QJraRI7proSKajFjmIDc7G8ftori5fk5
"""

def solve(board):
    """
    Solve the Sudoku board using a brute-force approach.
    """
    # Find an empty cell
    for i in range(9):
        for j in range(9):
            if board[i][j] == 0:
                # Try all possible values
                for value in range(1, 10):
                    if is_valid(board, i, j, value):
                        # Make the move
                        board[i][j] = value
                        # Recursively solve the rest of the board
                        if solve(board):
                            return True
                        # Undo the move
                        board[i][j] = 0
                # We tried all values and none of them worked, so backtrack
                return False
    # No empty cells, the board is solved
    return True

def is_valid(board, row, col, value):
    """
    Check if it's safe to place `value` at the given `row` and `col`.
    """
    # Check row constraints
    for i in range(9):
        if board[row][i] == value:
            return False
    # Check column constraints
    for i in range(9):
        if board[i][col] == value:
            return False
    # Check 3x3 box constraints
    box_row = row // 3
    box_col = col // 3
    for i in range(3):
        for j in range(3):
            if board[box_row * 3 + i][box_col * 3 + j] == value:
                return False
    # No constraints were violated, so it's safe
    return True

# Test the solver
board = [
    [5, 3, 0, 0, 7, 0, 0, 0, 0],
    [6, 0, 0, 1, 9, 5, 0, 0, 0],
    [0, 9, 8, 0, 0, 0, 0, 6, 0],
    [8, 0, 0, 0, 6, 0, 0, 0, 3],
    [4, 0, 0, 8, 0, 3, 0, 0, 1],
    [7, 0, 0, 0, 2, 0, 0, 0, 6],
    [0, 6, 0, 0, 0, 0, 2, 8, 0],
    [0, 0, 0, 4, 1, 9, 0, 0, 5],
    [0, 0, 0, 0, 8, 0, 0, 7, 9]
]

for i in board:
  print(i)

print(".")
solve(board)

for row in board:
    print(row)